# documentation: https://www.authelia.com
# slogan: The Single Sign-On Multi-Factor portal for web apps
# tags: authentiction,authorization
# logo: svgs/your-service.svg
# port: 9091

services:
  authelia:
    image: authelia/authelia:4.39.0
    container_name: authelia
    volumes:
      - ./config:/config
    labels:
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
    ports:
      - 9091:9091/tcp
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin